---
title: "Distribution of loans"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='last'}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='last'}
accounts <- read.csv("/Users/zhiyulin/anly503/fall2020/anly503-fall2020-a5-zlds123/data/accounts_analytical.csv")
transactions <- read.csv("/Users/zhiyulin/anly503/fall2020/anly503-fall2020-a5-zlds123/data/transactions.csv")
loans <- accounts[, grepl( "loan" , names(accounts))]
loans <- na.omit(loans)
```


```{r, echo=FALSE, warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='last'}
library(caret)
library(tidyverse)
library(ggplot2)
library(dplyr)
loans %>% 
  select(c("loan_amount", "loan_payment", "loan_term", "debit_bank_transfer_loan_payment_txn_ct", "debit_bank_transfer_loan_payment_txn_tot", "debit_bank_transfer_loan_payment_avg_txn", "loan_default")) %>%
  gather(key = "variable", value = "value", -one_of("loan_default")) %>%
  ggplot(aes(x = value, color=loan_default)) +
    geom_density() +
    facet_wrap(~variable, scales = 'free') 
```

This visualization shows default and non-default loans for all the numerical variables regarding loans. We can see that loan amounts are left-skewed whereas loan term are more uniformally distribured. 